### PR TITLE
Fix OGC bugs

### LINKED ISSUE #573: OGC filter with unparsable XML throws NPE
Doing the IT:

```
get(Arrays.asList(
                            new ImmutablePair<>("SERVICE", "WFS"),
                            new ImmutablePair<>("VERSION", "2.0.0"),
                            new ImmutablePair<>("COUNT", "1000"),
                            new ImmutablePair<>("REQUEST", "GetFeature"),
                            new ImmutablePair<>("FILTER", "<Filter xmlns:wfs=\\\"http://www.opengis.net/wfs/2.0\\\"><PropertyIsEqualTo matchAction=\\\"Any\\\" " +
            "matchCase=\\\"true\\\"><ValueReference>id</ValueReference><Literal>ID__170__20DI</Literal></PropertyIsEqualTo></Filter>")),
                            new Filter())
```

it throws a NPE instead of a SAX Exception.
It arrives in `ElasticFilter` at:

`} catch (SAXException e) {
                throw filterToElastic.ogcException;`

but `filterToElastic.ogcException` is null

### LINKED ISSUE #582: OGC Spatial Filters (within, BBOX, ...) throws Invalid parameter exception for valid geomtry fields
## Steps to reproduce

1. Start ARLAS-server with `ARLAS_SERVICE_WFS_ENABLE=true` 
2. Run the `CollectionTool.java` main to index IT data
3. Apply the following `GetFeature` request with a OGC Filter : `within` on `geo_params.geometry`

```
http://localhost:9999/arlas/ogc/wfs/geodata?request=GetFeature&version=2.0.0&filter=%3CFilter%20xmlns:wfs=%22http://www.opengis.net/wfs/2.0%22%20xmlns:gml=%22http://www.opengis.net/gml/3.2%22%3E%3CWithin%3E%3CValueReference%3Egeo_params.geometry%3C/ValueReference%3E%3Cgml:Polygon%20gml:id=%22P1%22%20srsName=%22http://www.opengis.net/def/crs/epsg/0/4326%22%3E%3Cgml:exterior%3E%3Cgml:LinearRing%3E%3Cgml:posList%3E10%2010%2020%2020%2030%2030%2040%2040%2010%2010%3C/gml:posList%3E%3C/gml:LinearRing%3E%3C/gml:exterior%3E%3C/gml:Polygon%3E%3C/Within%3E%3C/Filter%3E
```

### LINKED ISSUE #583: OGC Spatial Filters : Handle invalid geometries exception
If we pass a OGC spatial filter with an invalid Geometry, the exception is not managed and arrive to Elasticsearch.

Exemple of ArlasServer response after a not valid geometry : 
```
{"status":500,"message":"Cannot fetch features : RemoteTransportException[[tizintest][127.0.0.1:9300][indices:data/read/search]]; nested: SearchPhaseExecutionException[all shards failed]; nested: QueryShardException[failed to create query: {\n  \"bool\" : {\n    \"filter\" : [\n      {\n        \"match_all\" : {\n          \"boost\" : 1.0\n        }\n      },\n      {\n        \"bool\" : {\n          \"filter\" : [\n            {\n              \"bool\" : {\n                \"must\" : [\n                  {\n                    \"match_all\" : {\n                      \"boost\" : 1.0\n                    }\n                  }\n                ],\n                \"filter\" : [\n                  {\n                    \"geo_shape\" : {\n                      \"geo_params.geometry\" : {\n                        \"shape\" : {\n                          \"type\" : \"polygon\",\n                          \"orientation\" : \"right\",\n                          \"coordinates\" : [\n                            [\n                              [\n                                10.0,\n                                10.0\n                              ],\n                              [\n                                20.0,\n                                20.0\n                              ],\n                              [\n                                30.0,\n                                30.0\n                              ],\n                              [\n                                40.0,\n                                40.0\n                              ],\n                              [\n                                10.0,\n                                10.0\n                              ]\n                            ]\n                          ]\n                        },\n                        \"relation\" : \"within\"\n                      },\n                      \"ignore_unmapped\" : false,\n                      \"boost\" : 1.0\n                    }\n                  }\n                ],\n                \"adjust_pure_negative\" : true,\n                \"boost\" : 1.0\n              }\n            }\n          ],\n          \"adjust_pure_negative\" : true,\n          \"boost\" : 1.0\n        }\n      }\n    ],\n    \"adjust_pure_negative\" : true,\n    \"boost\" : 1.0\n  }\n}]; nested: NotSerializableExceptionWrapper[invalid_shape_exception: Cannot determine orientation: edges adjacent to (10.0,10.0) coincide];","error":"io.arlas.server.exceptions.InternalServerErrorException"}
```

### PR DESCRIPTION
**Pull request by MohamedHamouGisaia**
- Fix #583 
- Fix #573

### CODE REVIEW

File: ogc-common/src/main/java/io/arlas/server/exceptions/OGC/OGCException.java [hunk 1]
```diff
@@ -88,6 +89,7 @@ public OGCException(OGCExceptionCode exceptionCode, String exceptionText, Servic
     }
 
     public OGCException(List<OGCExceptionMessage> exceptionMessages, Service service) {
+        super(exceptionMessages.stream().filter(em -> (em.getExceptionTexts() != null && !em.getExceptionTexts().isEmpty())).map(em -> em.getExceptionTexts().stream().reduce((a, b) -> a + "\t" + b).orElse("")).reduce((a, b) -> a + "\t" + b).orElse(""));
```
Comment (laurent-thiebaud-gisaia) [inline ogc-common/src/main/java/io/arlas/server/exceptions/OGC/OGCException.java]: Did you test with .collect(Collectors.joining("\t")) ? It may avoid the need of the `orElse` and it is more readable.
There may be also some CollectionUtils.isEmpty(em.getExceptionTexts()) in order to avoid the need of the null check.

File: ogc-common/src/main/java/io/arlas/server/exceptions/OGC/OGCException.java [hunk 2]
```diff
@@ -98,6 +100,7 @@ public String getVersion() {
     }
 
     public OGCException(OGCExceptionMessage exceptionMessage, Service service) {
+        super(exceptionMessage.getExceptionTexts().stream().reduce((a, b) -> a + "\n" + b).orElse(""));
```
Comment (laurent-thiebaud-gisaia) [inline ogc-common/src/main/java/io/arlas/server/exceptions/OGC/OGCException.java]: Same comment

File: ogc-common/src/main/java/io/arlas/server/exceptions/OGC/OGCException.java [hunk 3]
```diff
@@ -113,4 +116,10 @@ public Response getResponse() {
                 .type(MediaType.APPLICATION_XML).build();
         return response;
     }
+
+    public static OGCException getInternalServerException(Exception e, Service service, String locator) {
+        List<OGCExceptionMessage> ogcExceptionMessages = new ArrayList<>();
```
Comment (laurent-thiebaud-gisaia) [inline ogc-common/src/main/java/io/arlas/server/exceptions/OGC/OGCException.java]: You may use Arrays.asList(...) to make it more readable

File: ogc-common/src/main/java/io/arlas/server/ogc/common/requestfilter/FilterToElasticHelper.java [hunk 4]
```diff
@@ -151,6 +159,17 @@ void visitGeoShapeBinarySpatialOperator(BinarySpatialOperator filter, Expression
             }
             e2.accept(delegate, extraData);
             shapeBuilder = delegate.currentShapeBuilder;
+            try {
+                GeoJsonObject object = GeoTypeMapper.getGeoJsonObject(shapeBuilder);
+                Geometry geometry = this.geometry.evaluate(object, Geometry.class);
+                CheckParams.checkWKT(geometry.toString());
+            } catch (ArlasException e) {
+                LOGGER.debug(e.getMessage());
+                List<OGCExceptionMessage> wfsExceptionMessages = new ArrayList<>();
```
Comment (laurent-thiebaud-gisaia) [inline ogc-common/src/main/java/io/arlas/server/ogc/common/requestfilter/FilterToElasticHelper.java]: Some comment with Arrays.asList

File: ogc-common/src/main/java/io/arlas/server/ogc/common/requestfilter/FilterToElasticHelper.java [hunk 5]
```diff
@@ -151,6 +159,17 @@ void visitGeoShapeBinarySpatialOperator(BinarySpatialOperator filter, Expression
...
+                wfsExceptionMessages.add(new OGCExceptionMessage(OGCExceptionCode.INVALID_PARAMETER_VALUE, e.getMessage() + " ["+ geometry + "]" , "filter"));
+                delegate.ogcException = new OGCException(wfsExceptionMessages, Service.WFS);
+                throw new RuntimeException();
```
Comment (laurent-thiebaud-gisaia) [inline ogc-common/src/main/java/io/arlas/server/ogc/common/requestfilter/FilterToElasticHelper.java]: Why do you need to throw a RunTime Excp without text? It looks unusual

Comment (MohamedHamouGisaia) [reply ogc-common/src/main/java/io/arlas/server/ogc/common/requestfilter/FilterToElasticHelper.java]: FIxed

File: ogc-common/src/main/java/io/arlas/server/ogc/common/requestfilter/FilterToElasticHelper.java (hunk 4 above)
Comment (MohamedHamouGisaia) [reply ogc-common/src/main/java/io/arlas/server/ogc/common/requestfilter/FilterToElasticHelper.java]: Fixed

File: ogc-common/src/main/java/io/arlas/server/exceptions/OGC/OGCException.java (hunk 3 above)
Comment (MohamedHamouGisaia) [reply ogc-common/src/main/java/io/arlas/server/exceptions/OGC/OGCException.java]: Fixed

File: ogc-common/src/main/java/io/arlas/server/exceptions/OGC/OGCException.java (hunk 2 above)
Comment (MohamedHamouGisaia) [reply ogc-common/src/main/java/io/arlas/server/exceptions/OGC/OGCException.java]: Fixed

File: ogc-common/src/main/java/io/arlas/server/exceptions/OGC/OGCException.java (hunk 1 above)
Comment (MohamedHamouGisaia) [reply ogc-common/src/main/java/io/arlas/server/exceptions/OGC/OGCException.java]: Fixed

File: ogc-common/src/main/java/io/arlas/server/exceptions/OGC/OGCException.java [hunk 6]
```diff
@@ -88,6 +92,7 @@ public OGCException(OGCExceptionCode exceptionCode, String exceptionText, Servic
     }
 
     public OGCException(List<OGCExceptionMessage> exceptionMessages, Service service) {
+        super(exceptionMessages.stream().filter(em -> (!CollectionUtils.isEmpty(em.getExceptionTexts()))).map(em -> em.getExceptionTexts().stream().collect(Collectors.joining("\t"))).collect(Collectors.joining("\t")));
```
Comment (laurent-thiebaud-gisaia) [inline ogc-common/src/main/java/io/arlas/server/exceptions/OGC/OGCException.java]: I think you can use a flatMap instead, this will avoid the double `.collect`

File: ogc-common/src/main/java/io/arlas/server/ogc/common/requestfilter/ElasticFilter.java [hunk 7]
```diff
@@ -86,19 +90,36 @@ public static BoolQueryBuilder filter(String constraint, CollectionReferenceDesc
...
-
+                org.opengis.filter.Filter openGisFilter = (org.opengis.filter.Filter)parser.parse(stream);
                 filterToElastic.encode(openGisFilter);
                 ObjectMapper mapper = new ObjectMapper();
                 String filterQuery = mapper.writeValueAsString(filterToElastic.getQueryBuilder());
                 // TODO : find a better way to remove prefix xml in field name
                 boolQuery.filter(QueryBuilders.wrapperQuery(filterQuery.replace("tns:", "")));
             } catch (SAXException e) {
-                throw filterToElastic.ogcException;
+                if (filterToElastic.ogcException != null) {
```
Comment (laurent-thiebaud-gisaia) [inline ogc-common/src/main/java/io/arlas/server/ogc/common/requestfilter/ElasticFilter.java]: I feel like the same code is repeated 3 times, maybe it can be put in a dedicated method?

File: ogc-common/src/main/java/io/arlas/server/exceptions/OGC/OGCException.java [hunk 8]
```diff
@@ -88,6 +92,7 @@ public OGCException(OGCExceptionCode exceptionCode, String exceptionText, Servic
     }
 
     public OGCException(List<OGCExceptionMessage> exceptionMessages, Service service) {
+        super(exceptionMessages.stream().filter(em -> (!CollectionUtils.isEmpty(em.getExceptionTexts()))).flatMap(em -> em.getExceptionTexts().stream()).collect(Collectors.joining("\t")));
```
Comment (laurent-thiebaud-gisaia) [inline ogc-common/src/main/java/io/arlas/server/exceptions/OGC/OGCException.java]: Last point: you may use `CollectionUtils.isNotEmpty` to be even more readable
