### PR TITLE
Fix bug when creating xml response of GetFeature

### LINKED ISSUE #616: NullPointer exception thrown when writing xml after a GetFeature or GetFeatureById request

### PR DESCRIPTION
**Pull request by MohamedHamouGisaia**
- NullPointer exception for keys of type object that have no nested objects
- NullPointer exception for keys of type date that doesn't have a format

Fix #616

### CODE REVIEW

File: ogc-common/src/main/java/io/arlas/server/ogc/common/utils/XmlUtils.java [hunk 1]
```diff
@@ -68,47 +71,38 @@ public static void parsePropertiesXsd(Map<String, CollectionReferenceDescription
...
+                           if (valueObject != null && property.type != ElasticType.DATE && property.type != ElasticType.GEO_POINT && property.type != ElasticType.GEO_SHAPE) {
+                               String value = valueObject.toString();
+                               writeElement(writer, String.join(".", new ArrayList<>(namespace)), value, uri, prefix);
+                           }else if(valueObject != null && property.type == ElasticType.DATE ){
+                               SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSXX");
+                               f.setTimeZone(TimeZone.getTimeZone("UTC"));
+                               if (property.format == null) {
+                                   property.format = CollectionReference.DEFAULT_TIMESTAMP_FORMAT;
+                               }
+                               Long timestamp = TimestampTypeMapper.getTimestamp(valueObject,property.format);
```
Comment (laurent-thiebaud-gisaia) [inline ogc-common/src/main/java/io/arlas/server/ogc/common/utils/XmlUtils.java]: Not sure the timestamp variable is used

Comment (MohamedHamouGisaia) [reply ogc-common/src/main/java/io/arlas/server/ogc/common/utils/XmlUtils.java]: my bad, I didn't put the right variable. I fixed it
