### PR TITLE
Fix updateResponse when no propagation

### LINKED ISSUE #461: Tagger with no propagation does not return status information

### PR DESCRIPTION
**Pull request by alainbodiguel**
Fix #461 #470

### CODE REVIEW

File: scripts/start-tagger.sh [hunk 1]
```diff
@@ -0,0 +1,21 @@
+#!/bin/sh
```
Comment (sylvaingaudan) [inline scripts/start-tagger.sh]: If the file is a docker resource, then it should be placed in docker-resources

Comment (alainbodiguel) [reply scripts/start-tagger.sh]: My bad, it's already there. I'll remove it.

**Comment by MohamedHamouGisaia** [comment]
LGTM
