### PR TITLE
return one or multiple geometries in _geosearch responses

### LINKED ISSUE #466: [Multi-geometry] return one or multiple geometries in _geosearch responses
Add a queryparam `returned_geometries` in explore API endpoints which is a comma separated geometry field_paths.

This parameter indicates which geometries to return : 
- For `_geosearch`
  - each returned hit fom ES need to be split to `N=sizeOf(returned_geometries)` features in the GeoJson :  100 hits from ES <==>  `N * 100` Features in `_geosearch` response.
 - each feature should contain an attribute `properties.geometry: "path_to_geo_field"` : 
  ```json
   {
      "type": "FeatureCollection",
      "features": [
         {
           "type": "Feature",
           "properties": {
              "feature_type": "hit",
              "geometry_path": "path_to_geometry_field",
              "data": {}
         },
         "geometry": {}
        }
      ]
   }
  ```

- For `_search`
  - `hit.md` should contain only the geometries asked in  `returned_geometries`
- `geometry` & `centroid` are reserved words and point respectively to **geometry_path** and **centroid_path** declared in the collection reference.
- if not specified, only  **geometry_path** is returned. If **geometry_path** is null, then **centroid_path** is returned (this is the current behaviour)
- throw an exception if conflict between  `returned_geometries` and `exclude` parameter

### PR DESCRIPTION
**Pull request by alainbodiguel**
Fix #466 return one or multiple geometries in _geosearch responses

### CODE REVIEW

File: arlas-rest/src/main/java/io/arlas/server/rest/explore/search/GeoSearchRESTService.java [hunk 1]
```diff
@@ -131,6 +133,13 @@ public Response geosearch(
                     required = false)
             @QueryParam(value = "exclude") String exclude,
 
+            @ApiParam(name = "returned_geometries",
+                    value = Documentation.PROJECTION_PARAM_RETURNED_GEOMETRIES,
+                    allowMultiple = true,
```
Comment (MohamedHamouGisaia) [inline arlas-rest/src/main/java/io/arlas/server/rest/explore/search/GeoSearchRESTService.java]: I'll change it to allowMultiple = false
