### PR TITLE
fix#180 improve WFSException

### LINKED ISSUE #180: Add Throwable cause to the constructor of WFSException

### PR DESCRIPTION
**Pull request by mbarbet**
fix #180

### CODE REVIEW

File: src/main/java/io/arlas/server/exceptions/WFSException.java [hunk 1]
```diff
@@ -41,7 +65,7 @@ public WFSException(WFSExceptionCode exceptionCode, String exceptionText, String
     }
 
     public WFSException(WFSExceptionCode exceptionCode, String exceptionText) {
-        this(exceptionCode, exceptionText, null);
+        this(exceptionCode, exceptionText, "null");
```
Comment (sfalquier) [inline src/main/java/io/arlas/server/exceptions/WFSException.java]: Nothing more relevant than "null" for locator value when not provided?
